name: MAUI Unit Tests

on:
  push:
    branches: [ main, Develop, Feature/* ]
  pull_request:
    branches: [ main, Develop, Feature/* ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI workloads
        run: |
          dotnet workload install maui
          dotnet workload install maui-android
          dotnet workload install maui-windows

      - name: Restore dependencies
        run: dotnet restore --runtime win-x64

      - name: Build application
        run: dotnet build --configuration Release --no-restore -f net8.0-windows10.0.19041.0 -r win-x64

      - name: Run unit tests
        run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
