name: MAUI Unit Tests

on:
  push:
    branches: [ main, Develop, Feature/* ]
  pull_request:
    branches: [ main, Develop, Feature/* ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI workloads
        run: |
          dotnet workload install maui
          dotnet workload install maui-android
          dotnet workload install maui-windows

      # Restore with explicit Windows runtime
      - name: Restore dependencies
        run: dotnet restore -r win-x64

      # Build the libraries first (they are standard .NET)
      - name: Build Core projects
        run: |
          dotnet build ./Grocery.Core/Grocery.Core.csproj --configuration Release --no-restore
          dotnet build ./Grocery.Core.Data/Grocery.Core.Data.csproj --configuration Release --no-restore

      # Build the MAUI app specifically for Windows
      - name: Build MAUI App
        run: dotnet build ./Grocery.App/Grocery.App.csproj --configuration Release --no-restore -p:RuntimeIdentifier=win-x64

      # Run tests 
      - name: Run unit tests
        run: dotnet test --configuration Release --no-build --verbosity normal
